### ISSUE TITLE
Panic when planning

### ISSUE THREAD

**Issue by mikenomitch** [hashicorp/nomad-pack#134]
I get this error when I try to plan a pack. It works properly when rendering and when running though.

```
➜  pack plan ./packs/promtail

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b422ab]

goroutine 1 [running]:
github.com/hashicorp/nomad-pack/internal/runner/job.formatTaskGroupDiff({0x0, 0xc0006908a0, 0x0, 0xc00009e618, 0xc000690890, 0x0}, 0x2, 0x0, {0x2036ed8, 0xc00054c8a0})
	/Users/mike/Code/nomad-pack/internal/runner/job/format.go:105 +0x3ab
github.com/hashicorp/nomad-pack/internal/runner/job.formatJobDiff({0xc00009e480, 0xc0006905f0, 0x0, 0xc00009e528, 0xc0006905e0}, 0x0, {0x2036ed8, 0xc00054c8a0})
	/Users/mike/Code/nomad-pack/internal/runner/job/format.go:90 +0x5a5
github.com/hashicorp/nomad-pack/internal/runner/job.(*Runner).outputPlannedJob(0xc00091fb08, {0x2036ed8, 0xc00054c8a0}, 0xc00022ea20, 0xc0004e7a80)
	/Users/mike/Code/nomad-pack/internal/runner/job/plan.go:118 +0xab
github.com/hashicorp/nomad-pack/internal/runner/job.(*Runner).PlanDeployment(0xc000540190, {0x2036ed8, 0xc00054c8a0}, 0xc00009e498)
	/Users/mike/Code/nomad-pack/internal/runner/job/plan.go:57 +0x627
github.com/hashicorp/nomad-pack/cli.(*PlanCommand).Run(0xc00009e1b0, {0xc0000300e0, 0x0, 0x0})
	/Users/mike/Code/nomad-pack/cli/plan.go:104 +0x659
github.com/mitchellh/cli.(*CLI).Run(0xc00012e140)
	/Users/mike/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
github.com/hashicorp/nomad-pack/cli.Main({0xc0000300c0, 0x3, 0x3})
	/Users/mike/Code/nomad-pack/cli/main.go:94 +0x2ad
main.main()
	/Users/mike/Code/nomad-pack/main.go:12 +0x7f
```

**Comment by jrasell** [comment]
@mikenomitch thanks for raising the issue, could you provide any additional details on how to reproduce this?

**Comment by mikenomitch** [comment]
I just tried to `nomad-pack plan promtail` with the code from this PR - https://github.com/hashicorp/nomad-pack-community-registry/pull/46

**Comment by mikenomitch** [comment]
Anybody have a current repro of this issue?
