### ISSUE TITLE
Nomad Pack Panics at job deployment on Nomad 0.9.7

### ISSUE THREAD

**Issue by robloxrob** [hashicorp/nomad-pack#279]
When attempting to deploy a Nomad job against Nomad 0.9.7 Nomad Pack Panics. While Nomad 0.9.7 may not be a supported target for nomad-pack, it is something we still have in many of our environments. The job does successfully deploy, but showing post deployment output crashes.

`root@docker-desktop:/deploy_variables# nomad-pack plan --var-file site/edge_proxy_services.hcl packs/edge_proxy_services/
+ Job: "haproxy-site-pack"
+ Task Group: "haproxy-site" (1 create)
  + Task: "haproxy-site" (forces create)  + Task: "haproxy-site" (forces create)  + Task: "haproxy-site-exporter" (forces create)

» Scheduler dry-run:
- All tasks successfully allocated.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xf73522]

goroutine 1 [running]:
github.com/hashicorp/nomad-pack/internal/runner/job.GetLocation(0x0, 0x1219fc1, 0x23, 0x203000)
	/home/circleci/project/project/internal/runner/job/format.go:502 +0x22
github.com/hashicorp/nomad-pack/internal/runner/job.formatDryRun(0xc00068f800, 0xc0003f10e0, 0x140ac28, 0xc0001886c0)
	/home/circleci/project/project/internal/runner/job/format.go:425 +0x536
github.com/hashicorp/nomad-pack/internal/runner/job.(*Runner).outputPlannedJob(0xc00053d9f0, 0x140ac28, 0xc0001886c0, 0xc0003f10e0, 0xc00068f800, 0xc00068f800)
	/home/circleci/project/project/internal/runner/job/plan.go:124 +0xa5
github.com/hashicorp/nomad-pack/internal/runner/job.(*Runner).PlanDeployment(0xc00053d9f0, 0x140ac28, 0xc0001886c0, 0xc00000c6f0, 0x0, 0xc00053d9a0, 0x1404508, 0xc00053d9f0)
	/home/circleci/project/project/internal/runner/job/plan.go:58 +0x578
github.com/hashicorp/nomad-pack/internal/cli.(*PlanCommand).Run(0xc00000c408, 0xc0000300c0, 0x3, 0x3, 0xc0004fa180)
	/home/circleci/project/project/internal/cli/plan.go:110 +0xc91
github.com/mitchellh/cli.(*CLI).Run(0xc000660640, 0xc00063fef8, 0xc00000e008, 0x1)
	/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x41a
github.com/hashicorp/nomad-pack/internal/cli.Main(0xc0000300a0, 0x5, 0x5, 0x0)
	/home/circleci/project/project/internal/cli/main.go:93 +0x225
main.main()
	/home/circleci/project/project/main.go:12 +0xa5`

CC @MillsyBot

**Comment by slonopotamus** [comment]
> it is something we still have in many of our environments

Is this still true in late 2023?

**Comment by tgross** [comment]
Doing a little issue cleanup. Nomad clusters this old are far out of support and no longer viable against current APIs. I'm going to close this out.
